apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hf-provisioner-digitalenergy
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ['*']
  - verbs:
      - '*'
    apiGroups:
      - provisioning.hobbyfarm.io
    resources:
      - instances
      - instances/status
      - keys
      - keys/status
  - verbs:
      - '*'
    apiGroups:
      - hobbyfarm.io
    resources:
      - virtualmachines
      - environments
      - virtualmachinetemplates
      - virtualmachines/status
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hf-provisioner-digitalenergy
rules:
  - apiGroups: ['provisioning.hobbyfarm.io']
    resources:
      - instances
      - instances/status
      - keys
      - keys/status
    verbs: ['*']
  - apiGroups: ['hobbyfarm.io']
    resources: ['virtualmachines', 'environments', 'virtualmachinetemplates', 'virtualmachines/status']
    verbs: ['*']
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hf-provisioner-digitalenergy
subjects:
  - kind: ServiceAccount
    name: {{ include "hf-provisioner-digitalenergy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: hf-provisioner-digitalenergy
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hf-provisioner-digitalenergy
subjects:
  - kind: ServiceAccount
    name: {{ include "hf-provisioner-digitalenergy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: hf-provisioner-digitalenergy
  apiGroup: rbac.authorization.k8s.io
